addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.4.3")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"   % "0.10.4")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"   % "2.5.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"  % "2.0.6")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release" % "1.5.11")
